### ISSUE TITLE
HTTP 200 / JsonParseException error in OwnTracks Android

### ISSUE THREAD

**Issue by Sukasa** [owntracks/recorder#237] opened 2018-05-12 18:24 UTC
Running the latest (as of posting the issue) ot-recorder package on Debian 9.

I have a VM set up with ot-recorder on my home network.  I am trying to make "Private HTTP" work on the Android app.  My understanding is that I should be able to use ot-recorder to handle the HTTP requests.

However, it is not working.  In the Android app I simply get "Error" as the endpoint state, and "HTTP 200, JsonParseException" as the Endpoint state message.

ot-recorder is set up to bind to 0.0.0.0, port 8080.  I have iptables doing prerouting for 80=>8080 TCP.  I am able to open the web interface on my PC and view the user/device list.  It shows the (working) test of the 'Private MQTT' mode I did previously.  However I already use nginx as a reverse proxy for various servers, including HTTPS encryption, and I would like to use this instead of opening up a separate port to another host on my network.

My OwnTracks HTTP host is currently set as "http://10.0.0.32/".  I have also tried "http://test:test@10.0.0.32/", where 10.0.0.32 is the IP address of the ot-recorder host.

I have tried setting passwords/information under 'identification' as well, however at no point have I been able to get anything other than a nondescript "HTTP 200, JsonParseException" to show up so I have no idea where to begin diagnosing what I have done wrong.

There is no useful information from systemctl status ot-recorder.  How can I determine why I am getting a JsonParseException and correct my settings so that ot-recorder can properly serve Private HTTP publishes from OwnTracks?

**Comment by jpmens** [comment] 2018-05-12 19:28
Thank you for your informative report and sorry you're experiencing problems. 

The best, to start with, would be to launch `ot-recorder --debug` manually using the ports, options you're using already. By this I mean disable it starting from systemd and do this manually in a terminal (no need to be _root_ unless you're using a port < 1024 as http port; actually we don't recommend you run it as _root_). 

If you could then show us what you see on the console when Android connects, it might give us a better idea of what's happening.

**Comment by Sukasa** [comment] 2018-05-12 19:51
sukasa@owntracks:~$ /usr/sbin/ot-recorder --debug owntracks/#
    ot-recorder[2238]: version 0.7.6 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
    ot-recorder[2238]: connecting to MQTT on [--snip--]:1883 as clientID ot-recorder-owntracks-2238 without TLS
    ot-recorder[2238]: HTTP listener started on 0.0.0.0:8080
    ot-recorder[2238]: Using storage at /var/spool/owntracks/recorder/store with precision 7
    ot-recorder[2238]: Subscribing to owntracks/# (qos=2)
    +++++ [owntracks/owntracks/ot-huawei (plen=122, r=1) [{"_type":"location","tid":"ei","acc":12,"batt":34,"conn":"w","lat":49.1751281,"lon":-123.9473161,"t":"u","tst":1526148710}]]
    --- AUTH --------------------------- / (121) (null) [auth=]
      Content-Type=application/json; charset=utf-8
      Content-Length=121
      Host=10.0.0.32
      Connection=Keep-Alive
      Accept-Encoding=gzip
      User-Agent=okhttp/3.8.0
    --- REQUEST --------------------------- / (121)  {"_type":"location","tid":"tr","acc":18,"batt":0,"lat":49.1751661,"lon":-123.9473461,"t":"u","tst":1526154343,"_cp":true} [auth=]
      Content-Type=application/json; charset=utf-8
      Content-Length=121
      Host=10.0.0.32
      Connection=Keep-Alive
      Accept-Encoding=gzip
      User-Agent=okhttp/3.8.0
    ------------------------------ / (121l) {"_type":"location","tid":"tr","acc":18,"batt":0,"lat":49.1751661,"lon":-123.9473461,"t":"u","tst":1526154343,"_cp":true}
      Content-Type=application/json; charset=utf-8
      Content-Length=121
      Host=10.0.0.32
      Connection=Keep-Alive
      Accept-Encoding=gzip
      User-Agent=okhttp/3.8.0
      ot-recorder[2238]: http: POST /
    --- AUTH --------------------------- / (121) {"_type":"location","tid":"tr","acc":18,"batt":0,"lat":49.1751661,"lon":-123.9473461,"t":"u","tst":1526154343,"_cp":true} [auth=]
      Content-Type=application/json; charset=utf-8
      Content-Length=121
      Host=10.0.0.32
      Connection=Keep-Alive
      Accept-Encoding=gzip
      User-Agent=okhttp/3.8.0
`

Config.otrc:

    {
    "_type":"configuration",
    "waypoints":[],
    "autostartOnBoot":true,
    "beaconBackgroundScanPeriod":30,
    "beaconForegroundScanPeriod":0,
    "beaconLayout":"m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
    "beaconMode":0,
    "cleanSession":false,
    "cmd":true,
    "cp":true,
    "httpSchedulerConsiderStrategyDirect":true,
    "ignoreInaccurateLocations":0,
    "ignoreStaleLocations":0,
    "locatorAccuracyBackground":1,
    "locatorAccuracyForeground":0,
    "locatorDisplacement":500,
    "locatorInterval":900,
    "mode":3,
    "notification":false,
    "notificationHigherPriority":false,
    "playOverride":false,
    "pubExtendedData":false,
    "ranging":false,
    "remoteConfiguration":true,
    "url":"http://10.0.0.32/"
    }

**Comment by Sukasa** [comment] 2018-05-12 19:53
Also as I have forgotten to include it:

Phone is a Huawei P10 (VTR-L09), running EMUI 8.0.0.321.  Android 8.0.0, April 1 security patch

**Comment by jpmens** [comment] 2018-05-12 20:45
In the first debug line, which starts with 

```
+++++ [owntracks/owntracks/ot-huawei (plen=122
```

there is an extraneous closing square bracket `]` at the end of the line. Is that a paste mistake, or is that really printed out? That would explain the JSON parse error.

**Comment by Sukasa** [comment] 2018-05-12 20:57
That's definitely printed out, and it's coming from MQTT.  That particular entry does show up in the table if I open http://10.0.0.32/ in a web browser

Relevant MQTT topic/message from mosquitto_sub: 
    owntracks/owntracks/ot-huawei {"_type":"location","tid":"ei","acc":12,"batt":34,
"conn":"w","lat":49.1751281,"lon":-123.9473161,"t":"u","tst":1526148710}

**Comment by Sukasa** [comment] 2018-05-12 21:01
Actually is it extraneous?  I see two opening square brackets in that line, with the other one prepended to the MQTT message payload

**Comment by l3d00m** [comment] 2018-05-23 19:29
Getting the same error. The list on the webpage stays empty to for me, there are no entires at all. Happening on a new setup, so I may did something wrong there.

**Comment by jpmens** [comment] 2018-05-23 19:33
@binarybucks can you comment on the JsonParseException? Under which circumstances would be be trigerred?

**Comment by jpmens** [comment] 2018-05-23 19:38
@Sukasa, @l3d00m can either of you capture and show what the Recorder is returning when your device POSTs a location with HTTP by inserting a proxy between device and Recorder? That would help probably to find the cause.

**Comment by binarybucks** [comment] 2018-05-23 19:40
And could you actually say which app version you are using?

**Comment by l3d00m** [comment] 2018-05-24 11:40
App Version 1.2.7 (newest from play store)

I just compiled the app on my own so I could view the log. The server output is the same as from @Sukasa 

I think the issue here is that the message does not get send to any endpoint? It just contacts the server's main url if I'm seeing that correctly.

Log from the app (I've added a ` Timber.v(r.body().string());` to print the result`:

```
05-24 13:37:59.328 28328-28328/org.owntracks.android.debug V/ServiceMessage/sendMessage/167: endpoint:org.owntracks.android.services.ServiceMessageHttp@e86340a, message:org.owntracks.android.messages.MessageLocation@910fec3
05-24 13:37:59.329 28328-28328/org.owntracks.android.debug V/ServiceMessage: onMessageQueued()- messageId:1527161879303, queueLength:1
05-24 13:37:59.333 28328-29856/org.owntracks.android.debug D/ServiceMessageHttp/postMessage/174: outgoing message:{"_type":"location","tid":"TL","acc":22,"batt":52,"conn":"w","lat":52.00000,"lon":10.00000,"t":"u","tst":1527161879}
05-24 13:37:59.335 28328-29856/org.owntracks.android.debug V/ServiceMessageHttp/postMessage/192: messageId:1527161879303, strategy:direct
05-24 13:37:59.336 28328-29856/org.owntracks.android.debug V/ServiceMessageHttp/prepareAndPostDirect/310: messageId:1527161879303
05-24 13:37:59.336 28328-29856/org.owntracks.android.debug V/ServiceMessageHttp/postMessage/209: url:http:/censored.org:8083, userInfo:null, messageId:1527161879303
05-24 13:37:59.366 28328-29856/org.owntracks.android.debug V/ServiceMessageHttp/postMessage/244: got HTTP response
05-24 13:37:59.368 28328-29856/org.owntracks.android.debug V/ServiceMessageHttp/postMessage/248: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
                                                                                                 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                                                                                                 <html xmlns="http://www.w3.org/1999/xhtml">
                                                                                                   <head>
                                                                                                     <title>Recorder</title>
                                                                                                     <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                     <meta name="mobile-web-app-capable" content="yes">
                                                                                                     <meta name="apple-mobile-web-app-capable" content="yes">
                                                                                                     <link rel="icon" sizes="192x192" href="static/recorder.png" />
                                                                                                     <link rel="apple-touch-icon" href="static/recorder.png" />
                                                                                                 
                                                                                                     <script src="static/js/jquery-1.12.0.min.js" type="text/javascript"></script>
                                                                                                     <script src="static/js/mustache.js" type="text/javascript"></script>
                                                                                                     <script src="static/js/moment.min.js" type="text/javascript"></script>
                                                                                                     <style>
                                                                                                     body, a, a:visited {
                                                                                                         font-family: Helvetica, sans-serif;
                                                                                                 	color: #3f72b5;
                                                                                                     }
                                                                                                     #usertable {
                                                                                                         font-family: Helvetica, sans-serif;
                                                                                                         width: 80%;
                                                                                                         border-collapse: collapse;
                                                                                                     }
                                                                                                 
                                                                                                     #usertable td, #usertable th {
                                                                                                         font-size: 1em;
                                                                                                         border: 1px solid #305e9f;
                                                                                                         padding: 3px 7px 2px 7px;
                                                                                                     }
                                                                                                 
                                                                                                     #usertable th {
                                                                                                         font-size: 1.1em;
                                                                                                         text-align: left;
                                                                                                         padding-top: 5px;
                                                                                                         padding-bottom: 4px;
                                                                                                         background-color: #305e9f;
                                                                                                 	color: white;
                                                                                                     }
                                                                                                     </style>
                                                                                                 
                                                                                                     <script type="text/javascript">
                                                                                                 
                                                                                                     function getuserlist() {
                                                                                                         var dataURI = location.protocol + "//" + location.host;
                                                                                                 
                                                                                                         var parts = location.pathname.split('/');
                                                                                                         for (var i = 1; i < parts.length - 1; i++) {
                                                                                                                 dataURI = dataURI + "/" + parts[i];
                                                                                                         }
                                                                                                         dataURI = dataURI + "/api/0/last" + location.search;
                                                                                                 
                                                                                                         console.log("dataURI = " + dataURI);
                                                                                                 
                                                                                                 	var now = moment();
                                                                                                 
                                                                                                 	var f12 = now.subtract(12, 'hours').utc().format('YYYY-MM-DDTHH:mm');
                                                                                                 	var f7 = now.subtract(7, 'days').utc().format('YYYY-MM-DDTHH:mm');
                                                                                                 	var f30 = now.subtract(30, 'days').utc().format('YYYY-MM-DDTHH:mm');
                                                                                                 
                                                                                                 	$.ajax({
                                                                                                 		url: dataURI,
                                                                                                 		type: "GET",
                                                                                                 		dataType: 'json',
                                                                                                 		success: function(data) {
                                                                                                 			// console.log(JSON.stringify(data));
                                                                                                 
                                                                                                 			for (var i = 0; i < data.length; i++) {
                                                                                                 				var d = data[i];
                                                                                                 				if (!d['_type']) {
                                                                                                 					console.log(d);
                                                                                                 					continue;
                                                                                                 				}
                                                                                                 				if (d.username == 'ping' && d.device == 'ping') {
                                                                                                 					continue;
                                                                                                 				}
                                                                                                 				d['udev'] = "user=" + d['username'] + "&device=" + d['device'];
                                                                                                 				d['f12'] = f12;
                                                                                                 				d['f7'] = f7;
                                                                                                 				d['f30'] = f30;
                                                                                                 
                                                                                                 	var line = "<tr><td>{{ username }} / {{ device }}</td>" +
                                                                                                 	"<td><a href='map/index.html?{{udev}}&format=geojson&from={{f12}}'>12h</a></td>" +
                                                                                                 	"<td><a href='map/index.html?{{udev}}&format=geojson&from={{f7}}'>7d</a></td>" +
                                                                                                 
                                                                                                 	"<td><a href='map/index.html?{{udev}}&format=linestring&from={{f12}}'>12h</a></td>" +
                                                                                                 	"<td><a href='map/index.html?{{udev}}&format=linestring&from={{f7}}'>7d</a></td>" +
                                                                                                 	"<td><a href='map/index.html?{{udev}}&format=linestring&from={{f30}}'>30d</a></td>" +
                                                                                                 	"</tr>";
                                                                                                 
                                                                                                 				var row = Mustache.render(line, d);
                                                                                                 
                                                                                                 				$('#usertable > tbody:last-child').append(row);
                                                                                                 			}
                                                                                                 		},
                                                                                                 		error: function(jqXHR, textstatus, errorthrown) {
                                                                                                 			console.log(textstatus, errorthrown);
                                                                                                 			console.log(jqXHR.status + " " + jqXHR.responseText);
                                                                                                 		},
                                                                                                 	});
                                                                                                     }
                                                                                                 
                                                                                                     $(document).ready(function() {
                                                                                                 	getuserlist();
                                                                                                 
                                                                                                     });
                                                                                                 
                                                                                                     </script>
                                                                                                   </head>
                                                                                                   <body>
                                                                                                 <div>
                                                                                                   <ul>
                                                                                                   <li><a href="last/index.html">Live MAP of current locations</a></li>
                                                                                                   <li><a href="table/index.html">TABLE of current locations</a></li>
                                                                                                   </ul>
                                                                                                 </div>
                                                                                                 
                                                                                                     <div id='content'>
                                                                                                     <table id='usertable'>
                                                                                                       <thead>
                                                                                                         <tr><th>User/Device</th><th>Points</th><th>Points</th><th>Track</th><th>Track</th><th>Track</th></tr>
                                                                                                       </thead>
                                                                                                       <tbody>
                                                                                                       </tbody>
                                                                                                     </table>
                                                                                                     </div>
                                                                                                 
                                                                                                   </body>
                                                                                                 </html>
05-24 13:37:59.369 28328-29856/org.owntracks.android.debug E/ServiceMessageHttp/postMessage/260: error:JsonParseException responseCode:200
05-24 13:37:59.369 28328-29856/org.owntracks.android.debug W/System.err: java.io.IOException: closed
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:426)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:522)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:129)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:246)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1271)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.support.Parser.fromJson(Parser.java:51)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.services.ServiceMessageHttp.postMessage(ServiceMessageHttp.java:249)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.services.ServiceMessageHttp.prepareAndPostDirect(ServiceMessageHttp.java:311)
05-24 13:37:59.370 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.services.ServiceMessageHttp.postMessage(ServiceMessageHttp.java:193)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.services.ServiceMessageHttp.processOutgoingMessage(ServiceMessageHttp.java:355)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:157)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at org.owntracks.android.messages.MessageBase.run(MessageBase.java:124)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug W/System.err:     at java.lang.Thread.run(Thread.java:762)
05-24 13:37:59.371 28328-29856/org.owntracks.android.debug V/ServiceMessage: onMessageDelivered()-  messageId:1527161879303, queueLength:0
05-24 13:37:59.372 28328-29856/org.owntracks.android.debug V/GeocodingProvider/resolve/35: loading for service null
05-24 13:37:59.405 28328-28328/org.owntracks.android.debug V/ServiceNotification/updateNotificationOngoing/211: enabled:true, state:Fehler
05-24 13:37:59.415 28328-28328/org.owntracks.android.debug V/GeocodingProvider$MessageLocationResolverTask/onPostExecute/164: result run:1.0 result:censored message:org.owntracks.android.messages.MessageLocation@910fec3
05-24 13:37:59.417 28328-28328/org.owntracks.android.debug V/ServiceNotification/onMessageLocationGeocoderResult/379: for location: censored
05-24 13:37:59.420 28328-28328/org.owntracks.android.debug V/ServiceNotification/updateNotificationOngoing/211: enabled:true, state:Fehler
05-24 13:38:00.426 28328-28328/org.owntracks.android.debug D/InputTransport: Input channel constructed: fd=128
05-24 13:38:00.427 28328-28328/org.owntracks.android.debug D/ViewRootImpl@17ac41f[Toast]: setView = android.widget.LinearLayout{801236c V.E...... ......I. 0,0-0,0} touchMode=true
05-24 13:38:00.427 28328-28328/org.owntracks.android.debug D/ViewRootImpl@f692f0c[Toast]: dispatchDetachedFromWindow
05-24 13:38:00.443 28328-28328/org.owntracks.android.debug D/InputTransport: Input channel destroyed: fd=127
05-24 13:38:00.492 28328-28577/org.owntracks.android.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [534x132]-format:1
05-24 13:38:00.492 28328-28328/org.owntracks.android.debug D/ViewRootImpl@17ac41f[Toast]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
05-24 13:38:02.428 28328-28328/org.owntracks.android.debug D/InputTransport: Input channel constructed: fd=127
05-24 13:38:02.429 28328-28328/org.owntracks.android.debug D/ViewRootImpl@2cf2d35[Toast]: setView = android.widget.LinearLayout{dfa95ca V.E...... ......I. 0,0-0,0} touchMode=true
05-24 13:38:02.430 28328-28328/org.owntracks.android.debug D/ViewRootImpl@17ac41f[Toast]: dispatchDetachedFromWindow
05-24 13:38:02.442 28328-28328/org.owntracks.android.debug D/InputTransport: Input channel destroyed: fd=128
05-24 13:38:02.482 28328-28577/org.owntracks.android.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [268x132]-format:1
05-24 13:38:02.483 28328-28328/org.owntracks.android.debug D/ViewRootImpl@2cf2d35[Toast]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
05-24 13:38:04.418 28328-28328/org.owntracks.android.debug D/ViewRootImpl@2cf2d35[Toast]: dispatchDetachedFromWindow
05-24 13:38:04.429 28328-28328/org.owntracks.android.debug D/InputTransport: Input channel destroyed: fd=127
```

**Comment by jpmens** [comment] 2018-05-24 12:01
We've documented the following:

> If enabled at compile time (WITH_HTTP), the Recorder will accept OwnTracks-type JSON payloads via HTTP at the URL endpoint `/pub&u=username&d=device`

so please try that.

**Comment by l3d00m** [comment] 2018-05-24 12:49
"http://server.org:8083/pub" works as the URL. I think it should be made a bit more obvious directly in the app.

Sorry for the troubles.

**Comment by binarybucks** [comment] 2018-05-24 12:54
Why should it be made mor obvious in the app? You have to point it ot an endpoint that returns valid JSON. That doesn't have to be ot-recorder. If you point it to a wrong endpoint on your backend, it will not work.

**Comment by jpmens** [comment] 2018-05-24 14:14
It need not be made more obvious in the app and in fact cannot be, as @binarybucks correctly points out, as we don't know which back-end you'll be pointing it at: it need not be the Recorder.

What does have to be made more obvious **to me** is the URL you're using; sorry about the delay in understanding where the problem lies.

**Comment by Sukasa** [comment] 2018-05-25 04:19
Correcting the url to "http://.../pub?u=sukasa&d=huawei" has corrected the issue.  I apparently missed that part of the documentation.

**Comment by jpmens** [comment] 2018-05-25 06:00
Thank you for reporting back. I'm glad you both were able to solve the issue.

**Closed by jpmens** 2018-05-25 06:00 UTC

**Comment by sm2x** [comment] 2019-01-14 09:06
This error still exists if the Endpoint is traccar V4.2

**Comment by jpmens** [comment] 2019-01-14 09:08
@sm2x if you are experiencing a similar issue with Android against Traccar, please open a new issue with details -- this is the Recorder issue tracker and as such not relevant.

**Comment by psoberoi** [comment] 2019-07-01 23:29
I ran into this as well. I agree there's no software bug here, but this is an easy mistake to make. The easiest way to experiment with Owntracks is to use recorder in HTTP mode, so it would be nice if this setup was well documented - maybe in a note at the top of https://owntracks.org/booklet/tech/http/.

**Comment by jpmens** [comment] 2019-07-03 14:27
@psoberoi we would entertain a PR with that documentation.

**Comment by psoberoi** [comment] 2019-07-03 16:11
Created https://github.com/owntracks/booklet/pull/44

Is there a "getting started" section that should also be edited? My quick search did not find one, but I could have easily missed it.

**Comment by jpmens** [comment] 2019-07-03 17:54
I think that's fine. Thank you.
