### ISSUE TITLE
User management and login enhancement

### ISSUE THREAD

**Issue by shadowjig** [owntracks/recorder#488] opened 2024-08-08 18:12 UTC
Create a user management system.  Basic Auth doesn't work with some password managers.  So it's a pain to access the web page with long secure passwords.  Also it would remove one less barrier to setting up Owntracks (for example setting up basic auth with a reverse proxy).  Also this user management system could be used to admin shared geofences, you could group people together, and add the encryption phrases.

**Comment by jpmens** [comment] 2024-08-08 18:28
Thanks for your suggestion, but I don't think we will be doing this. The Recorder shouldn't be managing users; it was never designed with that in mind and that task ought to be left to code which fronts the Recorder.

I am marking this as a duplicate of https://github.com/owntracks/quicksetup/issues/55

**Closed by jpmens** 2024-08-08 18:28 UTC

**Comment by shadowjig** [comment] 2024-08-08 21:20
Where can I request a feature that fronts the recorder?

**Comment by jpmens** [comment] 2024-08-09 06:18
You have already requested it, here. At least that's the way I understand your above request.

Now all you have to do is find someone who's willing to implement it. I don't know where you'll find that person. :-)
