### ISSUE TITLE
HTTP friend adding not working

### ISSUE THREAD

**Issue by amrul-jamrul** [owntracks/recorder#507] opened 2024-11-16 05:49 UTC
I have HTTP setup with docker compose and I am trying to add add friends. The local collection, table, and live map are all working. I crated a file that contained the required contents in the proper JSON format:
'name1-phone ["name1/android", "name2/phone"]`

I have written this into a file.txt and tried 

`ocat -S /store --load=friends < file.name` 
and 
`ocat --load=friends <<EOF
name-phone [ "name/android" ]
EOF`

But no matter what neither
`ocat -S TID --dump=friends`
or
`ocat --dump=friends`
ever show any outputs nor does it ever take effect on my devices. Am I missing something? Is there any more information that I should provide?

**Comment by jpmens** [comment] 2024-11-16 08:59
Sorry, you are having trouble, and I attribute that to how our tools work (or don't) in docker.

What you've done looks sensible and I see no fault there. I think what is happening is that you are likely using `docker run` in some form to run `ocat` which will attempt to open the database, write to it, etc. but this is not actually feasable as I assume the recorder is already running and thus has the LMDB database open. (There can only be one writer.)

I'm not sure exactly how to accomplish this, but I'd try stopping the Recorder, then running your `ocat --load=` and then restarting the Recorder.

I hope that makes some sense.

**Comment by amrul-jamrul** [comment] 2024-11-16 19:37
I've stopped the docker container and have tried running the `ocat` commands again, but they're still not functioning. 
`ocat --dump=friends` will return nothing and `cat -S TID --dump=friends` will return `Cannot open lmdb/friends at TID/ghash`.

**Comment by jpmens** [comment] 2024-11-16 22:48
When you stop the docker container, are you sure the volumes it uses for OwnTracks data are still there, i.e. are not destroyed / removed?

That second command you show `cat -S` makes no sense to me. a) I think you mean `ocat` and b) it looks as though something's missing ...

It's not possible, I think, to show a single friend; `ocat --dump=friends` is your friend ( 😀 ) as you also initially used.

**Comment by amrul-jamrul** [comment] 2024-11-17 20:22
When the docker container is stopped I can confirm that the volumes exist with `docker volume ls`. 

Yes I did mean `ocat` not `cat` I've edited by post accordingly 

I'm not sure where to go from here if `ocat` does not edit the docker volumes even when the container is stopped.

**Comment by jpmens** [comment] 2024-11-17 20:42
Show us your docker compose file, please, and I'll try to reproduce.

**Comment by amrul-jamrul** [comment] 2024-11-17 21:40
`version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - config:/config
      - store:/store
    restart: unless-stopped
    environment:
      - OTR_PORT=0

volumes:
  store:
  config:`

**Comment by jpmens** [comment] 2024-11-18 09:51
Come to think of it, this is maybe not even possible:
- we can't load friends if the Recorder is running
- stopping the service (ie `docker compose down`) means we then can't run `docker compose exec` because the service is down.

**Comment by amrul-jamrul** [comment] 2024-11-19 00:33
Is there a way to edit the store volume with the required friends.txt info prior to starting the container? I'll give it a try, if that fails I'll just run the program baremetal instead.

**Comment by jpmens** [comment] 2024-11-19 08:55
The issue is not the friends.txt but the lmdb database it is loaded into. I don't know how to do that prior to container start; maybe there's some docker (not -compose) magic ...

Running baremetal will mean you first initialize the Recorder once (ot-recorder --initialize), then load the friends (ocat --load=friends < f.txt), then launch the recorder. Should be straightforward.

Be aware, that using MQTT for all this is preferable, as I think we point out in several places. :)

**Comment by amrul-jamrul** [comment] 2024-11-22 06:43
What is the path to the lmdb database within the container? Maybe it is possible to copy it out edit it and then place it back into the container? `docker cp`

**Comment by jpmens** [comment] 2024-11-22 08:30
We cannot support you with this, and IMO it's the wrong approach -- far too hacky. 

I note you've begin with the MQTT method, so I'm now closing this.

**Closed by jpmens** 2024-11-22 08:30 UTC

**Comment by atetzner** [comment] 2025-02-28 22:20
I just had a similar problem and probably found an easy solution for updating the friends database when using the recorder with Docker.

First regularly stop the recorder with `docker compose down`. After that use the following command, you can start a Docker container using the regular recorder image but without starting the recorder itself. Instead a regular shell is opened and one can use `ocat` to update the database:

```
docker run -ti --rm --volume config:/config --volume store:/store --entrypoint /bin/sh owntracks/recorder:latest
```

The "magic" here is the `--entrypoint` argument that tells Docker to start a shell instead of the recorder. The `--volume` argument ensures that the previously created volumes for `config` and `store` are available in the container, so that we can edit the database.

**Comment by truncsphere** [comment] 2025-03-06 20:08
> I just had a similar problem and probably found an easy solution for updating the friends database when using the recorder with Docker.
> 
> First regularly stop the recorder with `docker compose down`. After that use the following command to start a Docker container using the regular recorder image but without starting the recorder itself. Instead a regular shell is opened and one can use `ocat` to update the database:
> 
> ```
> docker run -ti --rm --volume config:/config --volume store:/store --entrypoint /bin/sh owntracks/recorder:latest
> ```
> 
> The "magic" here is the `--entrypoint` argument that tells Docker to start a shell instead of the recorder. The `--volume` argument ensures that the previously created volumes for `config` and `store` are available in the container, so that we can edit the database.

Still no luck here as I'm seeing the same error as before. 

+ Skipping open defaults file /config/recorder.conf: No such file or directory
