### ISSUE TITLE
Syntax error: /etc/defaults/ot-recorder

### ISSUE THREAD

**Issue by holgerkoch** [owntracks/recorder#81] opened 2016-02-10 14:33 UTC
Hi,

after a make install, there is a new Configfile

/etc/defaults/ot-recorder

with the content:

<pre>[root@alpha defaults]# cat ot-recorder
#(@)ot-recorder.default
#
# Specify global configuration options for the OwnTracks Recorder
# and its associated utilities to override compiled-in defaults.

# OTR_STORAGEDIR = "/var/spool/owntracks/recorder/store"
</pre>
If i removed the # to activate the line

OTR_STORAGEDIR = "/var/spool/owntracks/recorder/store"

i got the following error:

[root@alpha recorder-master]# ./ot-recorder  --host localhost --port 1883 'owntracks/#'
ot-recorder[9189]: Syntax error in /etc/defaults/ot-recorder:7 - syntax error

I played a little bit with different syntax, but can't figure out the correct one. Can you give me a hint?

Best regards

Holger

**Comment by jpmens** [comment] 2016-02-10 15:13
That looks fine to me, and I cannot reproduce here with that configuration. Can you tell me which OS/ version you're running? 

And are you quite sure there are no control characters or smart quotes or something in that file? ;-)

**Comment by jpmens** [comment] 2016-02-10 15:14
FWIW, that defaults file is optional; if you don't use it (ie. comment everything out), your compiled-in defaults (`config.mk`) are used. Nevertheless, I'd like to find out what's wrong.

**Comment by holgerkoch** [comment] 2016-02-10 17:22
It's a CentOS 6.7 Server with all updates installed.

[root@alpha cron.d]# cat /etc/*rele*
CentOS release 6.7 (Final)
12.5.30 cos6.build1205150826.19
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
cpe:/o:centos:linux:6:GA

Further, i can't see any special characters:

[root@alpha cron.d]# cat -vet /etc/defaults/ot-recorder
#(@)ot-recorder.default$
#$
# Specify global configuration options for the OwnTracks Recorder$
# and its associated utilities to override compiled-in defaults.$
$
 OTR_STORAGEDIR = "/var/spool/owntracks/recorder/store"$
[root@alpha cron.d]# ot-recorder --help
ot-recorder[14259]: Syntax error in /etc/defaults/ot-recorder:7 - syntax error

Holger

**Comment by jpmens** [comment] 2016-02-10 17:46
Which version of libconfig is installed? `rpm -qa | grep libconfig`

**Comment by holgerkoch** [comment] 2016-02-10 18:21
[root@alpha owntracks.holgerkoch.de]# rpm -qa | grep libconfig
libconfig-1.3.2-1.1.el6.x86_64
libconfig-devel-1.3.2-1.1.el6.x86_64

**Comment by jpmens** [comment] 2016-02-10 18:45
I'm a little bit stumped, but I think this is a bug in `libconfig`. (I have 1.4.9-5 here.)

Trying to reproduce, this happens when e.g. a double quote is missing at the end of a string. Would you do me a favor please and

1. add a few spaces to the end of the `OTR_STORAGEDIR` line (behind the closing double quotes)
2. add one or two blank lines to the end of the file.

I'm just stabbing in the dark, in case you hadn't noticed ...

**Comment by jpmens** [comment] 2016-02-11 07:07
Would you please also see what happens if you

1. remove the quotes from the value entirely: `OTR_STORAGEDIR = /var/spool/owntracks/recorder/store`
2. squashing the spaces around the `=`: `OTR_STORAGEDIR="/var..."`
3. comment out the line completely by inserting a `#`

**Comment by jpmens** [comment] 2016-02-11 07:27
I can reproduce the syntax error with libconfig 1.3.2: the syntax has changed. Settings in libconfig 1.3.2 require a trailing semicolon:

```
OTR_STORAGEDIR = "/var/spool/owntracks/recorder/store"  ;
```

**Closed** 2016-02-11 07:41 UTC

**Comment by holgerkoch** [comment] 2016-02-11 18:28
Hi,
i can confirm, it's working with a trailing semicolon.
Thank you very much for yout help.

Best regards

Holger
