### ISSUE TITLE
/usr/share/doc/ot-recorder/ot-recorder.service not found during install (Ubuntu 24.04, x86-64, ot-recorder 0.9.9)

### ISSUE THREAD

**Issue by thromer** [owntracks/recorder#513] opened 2024-11-30 21:06 UTC
```
# apt -y install ot-recorder
...
The following NEW packages will be installed:
  ot-recorder
Preparing to unpack .../ot-recorder_0.9.9-0-deb12.7_amd64.deb ...
Unpacking ot-recorder (0.9.9-0-deb12.7) ...
Setting up ot-recorder (0.9.9-0-deb12.7) ...
install: cannot stat '/usr/share/doc/ot-recorder/ot-recorder.service': No such file or directory
...
```

Running on Ubuntu 24.04 x86-64

Maybe similar to #261

Workaround: copy the file from https://raw.githubusercontent.com/owntracks/recorder/refs/heads/master/debian/ot-recorder.service and re-run apt install

**Comment by jpmens** [comment] 2024-12-01 09:45
This should have been raised much earlier, and I cannot actually see that occurring. The package has the file `ot-recorder.service` in the specified directory:

```console
$ ls -l /usr/share/doc/ot-recorder
total 60
-rwxr-xr-x 1 root root 52474 Oct 28 09:49 README.md
-rw-r--r-- 1 root root   139 Oct 28 09:49 changelog.gz
-rwxr-xr-x 1 root root   290 Oct 28 09:49 ot-recorder.service
```

While the permissions of the file are incorrect, the file is there. Have you "visually" verified that it actually isn't there? I do realize "cannot stat" is quite precise, but I wonder whether it's due to the executable permissions.

**Comment by jpmens** [comment] 2024-12-01 10:00
Running on a brand new Ubuntu 24.04, I cannot reproduce this.

```console
# head -7 /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian

# curl --no-progress-meter https://raw.githubusercontent.com/owntracks/recorder/master/etc/repo.owntracks.org.gpg.key | sudo tee /etc/apt/trusted.gpg.d/owntracks.asc

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQINBFap9qABEADHD51G5Falcv1nEABzDOHRJ484kOIe8W1fzy84jqKxbm7VRh1s
Ji8taAbOHNg73cpaukLZtfXKPS4JIs1UH2wmiuQVV/QYm7QDsC0dFsc5EDYLllpv
vqN8X6BPgoHKb3sjcJ0cac56ACDX2hPDbsvNhLumgMqMxLZG8YejWdh4GhyCX5Xw
8fD7HT3gANoyOPKeqv9vlb/XG6a8cGG5I4HgB2kztf+6FkAgr97vUs5KeXTxQxdz
RSfufPXk0L7JVPyOlv/2rAlgAICbZQZcc8uXmBq9v6ezUyEh0C1olJUcWTWLxAQ3
O3C0PIbwZfHixE2fU7mMyS39Nf0lQLTpKmYWV7mwcUHp/JyQa87qaglSehcbguR8
Ny0lb4CvXeEkWFiuriPyhFAPIYz5Iqt277LlFrqoruuabtQC+dqf5mTmsLReIOpR
xsYeIwKdfbYlMJl9ucwvivEBol0trhBbyuTJ8U6DBob81fGIEusVKPZ25Fn8bMhT
/kRrIQEpJMjB4p03BgoGMoLjn5iZGYfM9mzECDnQ2mjS1PFeTBbRNRthN2pd6nrV
ln8zg40GAHP7xaaFHGv2glqGaqxLgp4ncBdJOD9QsMmMNRIe40c3XQAiNYfo+3ql
DRvSvCb3iU4Pupfeg1W106s+OGVzA7WrbNslrcchOgn/PGHy/HdW6aDIrQARAQAB
tDxPd25UcmFja3MgcGFja2FnZXMgKHBhY2thZ2Ugc2lnbmluZykgPHN1cHBvcnRA
b3dudHJhY2tzLm9yZz6JAjkEEwECACMFAlap9qACGwMHCwkIBwMCAQYVCAIJCgsE
FgIDAQIeAQIXgAAKCRC+FnUVPgpRFhQTD/48dgQewJHzVs+rcKNdSEygEHf84zR0
a5ggpVtBqbp2kKzj3A+jvnfyIc8gNGMLQR+tR/xLISixbx7zZPJErBUsJU9BPeev
/m0GxFoZXdPN48viRrkpWFapQyXxEzkxEHcBqRWi0puV36mBsbl7vgSmodilbhCH
Xyn70vZ3tC3nXhUt1E2gpAgck+fpmz2vbhJlETyICG5ymN34bcjLCCNem3QXNXb4
aN4KWAvSxDAbcmzLs3JIPiT7YOQFueTMs++PQmNC4joT08kO+nc6MMOaMeGCdTea
S8A53ulbMgQEO0HsWZpn1VE0dtbKi/LH+MMH0Cpftd7XPHLWBZ4OwjND8ETz6WhC
Ln14/w4h6QVT3632k0b80llWR3G0v1VhnAMVvJSYQHidxdubjMFA07e3KzXDuncx
0l6eF1QqO2O5LwzsDSuscUUCetLBrvO5odjDbr8Y4ghSWQOJjwdzuva5YWsUDrGy
PtQztyw7RD44ymR4xrg9iPdHbUTh5NRgUVG6m2BD9cLmhEmgrBX23Yht+3mMiYR8
ge0VHj565ZqUP8Vb5F+aB7H1fnsg+wsMASiExiOwFEZQHfNldg+6pxFs7HKOf0hR
vmkjG76XXo6PR82HAOAFtosUa67swJjQsaDAE4CxOXOiQNdIegqdiYGwDPtjvc23
HZce4lqbNNbz1A==
=PVJv
-----END PGP PUBLIC KEY BLOCK-----

# echo "deb  http://repo.owntracks.org/debian bookworm main" | sudo tee /etc/apt/sources.list.d/owntracks.list > /dev/null
# apt update
# apt install ot-recorder

Get:1 http://repo.owntracks.org/debian bookworm InRelease [3228 B]
Hit:2 http://mirrors.digitalocean.com/ubuntu noble InRelease
Hit:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu noble-updates InRelease
Hit:5 http://mirrors.digitalocean.com/ubuntu noble-backports InRelease
Hit:6 http://security.ubuntu.com/ubuntu noble-security InRelease
Get:7 http://repo.owntracks.org/debian bookworm/main amd64 Packages [728 B]
Fetched 3956 B in 1s (3356 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
188 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libconfig9 liblua5.4-0 libmosquitto1
The following NEW packages will be installed:
  libconfig9 liblua5.4-0 libmosquitto1 ot-recorder
0 upgraded, 4 newly installed, 0 to remove and 188 not upgraded.
Need to get 1906 kB of archives.
After this operation, 5377 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://repo.owntracks.org/debian bookworm/main amd64 ot-recorder amd64 0.9.9-0-deb12.7 [1662 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu noble/universe amd64 libconfig9 amd64 1.5-0.4build2 [23.2 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu noble/main amd64 liblua5.4-0 amd64 5.4.6-3build2 [166 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu noble/universe amd64 libmosquitto1 amd64 2.0.18-1build3 [54.1 kB]
Fetched 1906 kB in 0s (10.4 MB/s)
Selecting previously unselected package libconfig9:amd64.
(Reading database ... 71895 files and directories currently installed.)
Preparing to unpack .../libconfig9_1.5-0.4build2_amd64.deb ...
Unpacking libconfig9:amd64 (1.5-0.4build2) ...
Selecting previously unselected package liblua5.4-0:amd64.
Preparing to unpack .../liblua5.4-0_5.4.6-3build2_amd64.deb ...
Unpacking liblua5.4-0:amd64 (5.4.6-3build2) ...
Selecting previously unselected package libmosquitto1:amd64.
Preparing to unpack .../libmosquitto1_2.0.18-1build3_amd64.deb ...
Unpacking libmosquitto1:amd64 (2.0.18-1build3) ...
Selecting previously unselected package ot-recorder.
Preparing to unpack .../ot-recorder_0.9.9-0-deb12.7_amd64.deb ...
Unpacking ot-recorder (0.9.9-0-deb12.7) ...
Setting up libconfig9:amd64 (1.5-0.4build2) ...
Setting up libmosquitto1:amd64 (2.0.18-1build3) ...
Setting up liblua5.4-0:amd64 (5.4.6-3build2) ...
Setting up ot-recorder (0.9.9-0-deb12.7) ...
info: Selecting UID from range 100 to 999 ...

info: Adding system user `owntracks' (UID 109) ...
info: Adding new user `owntracks' (UID 109) with group `owntracks' ...
info: Not creating `/nonexistent'.
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
#
```

And the files are there:

```console
# ls -l /usr/share/doc/ot-recorder/
total 60
-rwxr-xr-x 1 root root 52474 Oct 28 08:49 README.md
-rw-r--r-- 1 root root   139 Oct 28 08:49 changelog.gz
-rwxr-xr-x 1 root root   290 Oct 28 08:49 ot-recorder.service
```

**Comment by thromer** [comment] 2024-12-02 00:19
Strange, I think I removed all vestiges of ot-recorder to simulate a clean install, and I still see the problem. If I manually install ot-recorder with dpkg -D333 for super-verbose debugging, I see these suspicious entries, but I don't have the patience to walk through the dpkg source to understand exactly why they occur and what they mean. Could be a red herring.

/usr/share/doc/ot-recorder does end up with changelog.gz, but not with README.md or ot-recorder.service

Heavily excerpted, full log attached.

# dpkg -D333 -i /var/cache/apt/archives/ot-recorder_0.9.9-0-deb12.7_amd64.deb | tee dpkg.log
D000010: filter comparing '/usr/share/doc/ot-recorder' and '/usr/share/doc/*'
D000010: filter removing ./usr/share/doc/ot-recorder
D000010: filter seeing if '/usr/share/doc/ot-recorder' needs to be reincluded
D000100: filter subpattern '/usr/share/doc'
D000010: filter reincluding ./usr/share/doc/ot-recorder
D000010: path_remove_tree '/usr/share/doc/ot-recorder.dpkg-new'
D000010: path_remove_tree '/usr/share/doc/ot-recorder.dpkg-tmp'
D000010: filter removing ./usr/share/doc/ot-recorder/ot-recorder.service
D000010: filter comparing '/usr/share/doc/ot-recorder/ot-recorder.service' and '/usr/share/doc/*/copyright'
D000010: filter comparing '/usr/share/doc/ot-recorder/ot-recorder.service' and '/usr/share/doc/*/changelog.*'
D000010: filter comparing '/usr/share/doc/ot-recorder/changelog.gz' and '/usr/share/man/*'
D000010: filter comparing '/usr/share/doc/ot-recorder/changelog.gz' a
nd '/usr/share/locale/*/LC_MESSAGES/*.mo'
D000010: filter comparing '/usr/share/doc/ot-recorder/changelog.gz' and '/usr/share/doc/*'
D000010: filter removing ./usr/share/doc/ot-recorder/changelog.gz

My only wild guess right now is that the behavior I'm seeing is triggered by running on a headless machine with a minimal install and somehow that trips things up.

[dpkg.log](https://github.com/user-attachments/files/17970875/dpkg.log)

**Comment by thromer** [comment] 2024-12-02 05:13
Aha, the trigger was that I installed a "minimal" Ubuntu image on my Oracle Cloud instance, which has a file that excludes dpkg from installing in /usr/share/doc.

The TL;DR, I think, is that it is risky for packages to place essential files in /usr/share/doc (and some other places, see below), at least for Ubuntu.

Details:

The minimal Ubuntu images have a file that instructs dpkg not to install documentation, by excluding /use/share/doc and some other paths.
```
$ cat /etc/dpkg/dpkg.cfg.d/excludes
# Drop all man pages
path-exclude=/usr/share/man/*

# Drop all translations
path-exclude=/usr/share/locale/*/LC_MESSAGES/*.mo

# Drop all documentation ...
path-exclude=/usr/share/doc/*

# ... except copyright files ...
path-include=/usr/share/doc/*/copyright

# ... and Debian changelogs for native & non-native packages
path-include=/usr/share/doc/*/changelog.*
```
The clues were

1. Looking at the main [commit](https://github.com/guillemj/dpkg/commit/4694cd6) for the dpkg [source file](https://github.com/guillemj/dpkg/blob/main/src/main/filters.c#L64) that produced the suspect "removing" log messages says "This provides support for filtering paths on package installation. This allows embedded systems to skip /usr/share/doc, manpages, etc."
1. When I ran the [unminimize](https://documentation.ubuntu.com/public-cloud/en/latest/all-clouds-explanation/ubuntu-base-and-minimal-images/#what-is-unminimize-what-does-it-do) command, roughly the first message was "Re-enabling installation of all documentation in dpkg..."

A workaround is to comment out the relevant path-exclude line in `/etc/dpkg/dpkg.cfg.d/excludes`, though that will affect all packages, not just ot-recorder.

**Comment by jpmens** [comment] 2024-12-02 07:12
Thank you for investigating that and your full report!

Indeed, we'll change this to save future headaches.

**Comment by jpmens** [comment] 2024-12-02 07:28
Fixed. Will be in next release.

**Closed by jpmens** 2024-12-02 07:28 UTC
Labels: bug
