### ISSUE TITLE
Install on RaspberryPi3b+ fails after upgrade from Stretch to Buster returns error

### ISSUE THREAD

**Issue by M-ax-G** [owntracks/recorder#356] opened 2020-10-26 02:52 UTC
I upgraded my RaspberryPi from Stretch to Buster a few days ago, which completed successfully.
A day later I noticed that ot-recorder did not run.
`sudo service ot-recorder status
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-10-21 18:45:49 AEST; 4 days ago
  Process: 443 ExecStartPre=/bin/sleep 15 (code=exited, status=0/SUCCESS)
  Process: 723 ExecStart=/usr/sbin/ot-recorder owntracks/# (code=exited, status=203/EXEC)
 Main PID: 723 (code=exited, status=203/EXEC)

Oct 21 18:45:07 rpi3ohv2 systemd[1]: Starting OwnTracks Recorder...
Oct 21 18:45:49 rpi3ohv2 systemd[1]: Started OwnTracks Recorder.
Oct 21 18:45:49 rpi3ohv2 systemd[723]: ot-recorder.service: Failed to execute command: No such file or directory
Oct 21 18:45:49 rpi3ohv2 systemd[723]: ot-recorder.service: Failed at step EXEC spawning /usr/sbin/ot-recorder: No such file or directory
Oct 21 18:45:49 rpi3ohv2 systemd[1]: ot-recorder.service: Main process exited, code=exited, status=203/EXEC
Oct 21 18:45:49 rpi3ohv2 systemd[1]: ot-recorder.service: Failed with result 'exit-code'.
`
Reading the readme.md and learned about the new repo for Buster.
I followed the steps:
`
sudo wget http://repo.owntracks.org/repo.owntracks.org.gpg.key
sudo apt-key add repo.owntracks.org.gpg.key
sudo echo "deb  http://repo.owntracks.org/debian buster main" > /etc/apt/sources.list.d/owntracks.list
sudo apt-get update
sudo apt-get install ot-recorder
`
which ended with an error:
`
sudo apt-get install ot-recorder
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libconfig9 libcurl3-gnutls libsodium23
The following NEW packages will be installed:
  libconfig9 libcurl3-gnutls libsodium23 ot-recorder
0 upgraded, 4 newly installed, 0 to remove and 6 not upgraded.
Need to get 920 kB of archives.
After this operation, 2,196 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://repo.owntracks.org/debian buster/main armhf ot-recorder armhf 0.8.4-0-deb10.2 [461 kB]
Get:2 http://mirror.datamossa.io/raspbian buster/main armhf libconfig9 armhf 1.5-0.4 [27.7 kB]
Get:3 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u1 [292 kB]
Get:4 http://mirror.datamossa.io/raspbian buster/main armhf libsodium23 armhf 1.0.17-1 [139 kB]
Fetched 920 kB in 32s (28.4 kB/s)
Selecting previously unselected package libconfig9:armhf.
(Reading database ... 49267 files and directories currently installed.)
Preparing to unpack .../libconfig9_1.5-0.4_armhf.deb ...
Unpacking libconfig9:armhf (1.5-0.4) ...
Selecting previously unselected package libcurl3-gnutls:armhf.
Preparing to unpack .../libcurl3-gnutls_7.64.0-4+deb10u1_armhf.deb ...
Unpacking libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Selecting previously unselected package libsodium23:armhf.
Preparing to unpack .../libsodium23_1.0.17-1_armhf.deb ...
Unpacking libsodium23:armhf (1.0.17-1) ...
Selecting previously unselected package ot-recorder.
Preparing to unpack .../ot-recorder_0.8.4-0-deb10.2_armhf.deb ...
Unpacking ot-recorder (0.8.4-0-deb10.2) ...
Setting up libconfig9:armhf (1.5-0.4) ...
Setting up libsodium23:armhf (1.0.17-1) ...
Setting up libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Setting up ot-recorder (0.8.4-0-deb10.2) ...
chown: cannot access '/usr/bin/ocat': No such file or directory
dpkg: error processing package ot-recorder (--configure):
 installed ot-recorder package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.28-10+rpi1) ...
Errors were encountered while processing:
 ot-recorder
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
Checking the status of the service revealed libsodium is missing.
`
sudo service ot-recorder status
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-10-26 10:04:13 AEST; 3s ago
  Process: 3164 ExecStartPre=/bin/sleep 15 (code=exited, status=0/SUCCESS)
  Process: 3171 ExecStart=/usr/sbin/ot-recorder owntracks/# (code=exited, status=127)
 Main PID: 3171 (code=exited, status=127)

Oct 26 10:03:57 rpi3ohv2 systemd[1]: Starting OwnTracks Recorder...
Oct 26 10:04:13 rpi3ohv2 systemd[1]: Started OwnTracks Recorder.
Oct 26 10:04:13 rpi3ohv2 ot-recorder[3171]: /usr/sbin/ot-recorder: error while loading shared libraries: libsodium.s
Oct 26 10:04:13 rpi3ohv2 systemd[1]: ot-recorder.service: Main process exited, code=exited, status=127/n/a
Oct 26 10:04:13 rpi3ohv2 systemd[1]: ot-recorder.service: Failed with result 'exit-code'.
`
I then felt that maybe uninstalling and doing a clean install would solve the problem...
`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libconfig9 libcurl3-gnutls libsodium23
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  ot-recorder
0 upgraded, 0 newly installed, 1 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 1,207 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 49603 files and directories currently installed.)
Removing ot-recorder (0.8.4-0-deb10.2) ...

 [2020-10-26 11:44] maxg@rpi3ohv2 ~ $ 
sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libconfig9 libcurl3-gnutls libsodium23
0 upgraded, 0 newly installed, 3 to remove and 11 not upgraded.
After this operation, 989 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 49294 files and directories currently installed.)
Removing libconfig9:armhf (1.5-0.4) ...
Removing libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Removing libsodium23:armhf (1.0.17-1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...

[2020-10-26 11:44] maxg@rpi3ohv2 ~ $ 
sudo apt install ot-recorder
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libconfig9 libcurl3-gnutls libsodium23
The following NEW packages will be installed:
  libconfig9 libcurl3-gnutls libsodium23 ot-recorder
0 upgraded, 4 newly installed, 0 to remove and 11 not upgraded.
Need to get 0 B/920 kB of archives.
After this operation, 2,196 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package libconfig9:armhf.
(Reading database ... 49268 files and directories currently installed.)
Preparing to unpack .../libconfig9_1.5-0.4_armhf.deb ...
Unpacking libconfig9:armhf (1.5-0.4) ...
Selecting previously unselected package libcurl3-gnutls:armhf.
Preparing to unpack .../libcurl3-gnutls_7.64.0-4+deb10u1_armhf.deb ...
Unpacking libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Selecting previously unselected package libsodium23:armhf.
Preparing to unpack .../libsodium23_1.0.17-1_armhf.deb ...
Unpacking libsodium23:armhf (1.0.17-1) ...
Selecting previously unselected package ot-recorder.
Preparing to unpack .../ot-recorder_0.8.4-0-deb10.2_armhf.deb ...
Unpacking ot-recorder (0.8.4-0-deb10.2) ...
Setting up libconfig9:armhf (1.5-0.4) ...
Setting up libsodium23:armhf (1.0.17-1) ...
Setting up libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Setting up ot-recorder (0.8.4-0-deb10.2) ...
chown: cannot access '/usr/bin/ocat': No such file or directory
dpkg: error processing package ot-recorder (--configure):
 installed ot-recorder package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.28-10+rpi1) ...
Errors were encountered while processing:
 ot-recorder
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
**chown: cannot access '/usr/bin/ocat': No such file or directory**
The file does not exist, but did exist before I upgraded to Buster.

Now I am at the end of my wits. Hence, any hints appreciated.

**Comment by grimpeur78** [comment] 2020-11-01 16:09
I've made a fresh install of my RPi 3b+ today and am facing the same issue when trying to install ot-recorder. Here's the output of apt:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ot-recorder
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/461 kB of archives.
After this operation, 1,207 kB of additional disk space will be used.
Selecting previously unselected package ot-recorder.
(Reading database ... 44263 files and directories currently installed.)
Preparing to unpack .../ot-recorder_0.8.4-0-deb10.2_armhf.deb ...
Unpacking ot-recorder (0.8.4-0-deb10.2) ...
Setting up ot-recorder (0.8.4-0-deb10.2) ...
chown: cannot access '/usr/bin/ocat': No such file or directory
chown: cannot access '/usr/sbin/ot-recorder': No such file or directory
dpkg: error processing package ot-recorder (--configure):
 installed ot-recorder package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 ot-recorder
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've also tried to manually install the most recent package downloaded from http://repo.owntracks.org/debian/pool/main/o/ot-recorder/ (version of 5 September 2020, 12:48), but it gives me the same error.

I've been using ot-recorder and owntracks for several months by now and love it. It'd be great if you guys could look into this issue. I guess there must be an error in the package file. Thanks!

**Comment by ctschach** [comment] 2021-01-13 09:17
Okay, the problem is, that the binaries are installed in

/usr/local/bin/ocat
/usr/local/sbin/ot-recorder

but the installer is expecting them in /usr/bin and /usr/sbin. I created a symbolic link and the installer passes.

Now in addition it's complaining that /usr/share/owntracks does not exists. So I link this to /var/spool/owntracks

**Comment by nonsintetic** [comment] 2021-09-06 19:02
Same problem on latest Raspbian Buster:
```
sudo apt-get install ot-recorder
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  ot-recorder
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/461 kB of archives.
After this operation, 1,207 kB of additional disk space will be used.
Selecting previously unselected package ot-recorder.
(Reading database ... 48233 files and directories currently installed.)
Preparing to unpack .../ot-recorder_0.8.4-0-deb10.2_armhf.deb ...
Unpacking ot-recorder (0.8.4-0-deb10.2) ...
Setting up ot-recorder (0.8.4-0-deb10.2) ...
/var/lib/dpkg/info/ot-recorder.postinst: 24: /var/lib/dpkg/info/ot-recorder.postinst: /usr/sbin/ot-recorder: Permission denied
dpkg: error processing package ot-recorder (--configure):
 installed ot-recorder package post-installation script subprocess returned error exit status 126
Errors were encountered while processing:
 ot-recorder
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jpmens** [comment] 2022-05-23 15:22
We have current packages in the repository. Kindly test, and if the issue persists, let us know.

**Closed by jpmens** 2022-05-23 15:22 UTC
